#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AsukaHasMatrix87

#include "Basic.hpp"

#include "HottaFramework_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AsukaHasMatrix87.AsukaHasMatrix87_C
// 0x0000 (0x0058 - 0x0058)
class UAsukaHasMatrix87_C final : public UHottaGameplayEffectCustomApplicationRequirement
{
public:
	bool CanApplyGameplayEffectContent(class AActor* SourceActor, class AActor* TargetActor, class AActor* InstigatorActor, const class UGameplayEffect* GameplayEffect) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AsukaHasMatrix87_C">();
	}
	static class UAsukaHasMatrix87_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAsukaHasMatrix87_C>();
	}
};
static_assert(alignof(UAsukaHasMatrix87_C) == 0x000008, "Wrong alignment on UAsukaHasMatrix87_C");
static_assert(sizeof(UAsukaHasMatrix87_C) == 0x000058, "Wrong size on UAsukaHasMatrix87_C");

}

