#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EternalWatcher

#include "Basic.hpp"

#include "BP_EternalWatcher_classes.hpp"
#include "BP_EternalWatcher_parameters.hpp"


namespace SDK
{

// Function BP_EternalWatcher.BP_EternalWatcher_C.ExecuteUbergraph_BP_EternalWatcher
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::ExecuteUbergraph_BP_EternalWatcher(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "ExecuteUbergraph_BP_EternalWatcher");

	Params::BP_EternalWatcher_C_ExecuteUbergraph_BP_EternalWatcher Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.TestCollision
// (BlueprintCallable, BlueprintEvent)

void ABP_EternalWatcher_C::TestCollision()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "TestCollision");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "ReceiveTick");

	Params::BP_EternalWatcher_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_EternalWatcher_C::BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_EternalWatcher_C_BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.BPOnMainRoleLoadFinished
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AHottaPlayerCharacter*            MainPlayer                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::BPOnMainRoleLoadFinished(class AHottaPlayerCharacter* MainPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "BPOnMainRoleLoadFinished");

	Params::BP_EternalWatcher_C_BPOnMainRoleLoadFinished Parms{};

	Parms.MainPlayer = MainPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.BndEvt__BP_EternalWatcher_RewardSpawner_K2Node_ComponentBoundEvent_2_AllVisualsHarvestedSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AHottaVisualSpawnManager*         InstigateSpawner                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::BndEvt__BP_EternalWatcher_RewardSpawner_K2Node_ComponentBoundEvent_2_AllVisualsHarvestedSignature__DelegateSignature(class AHottaVisualSpawnManager* InstigateSpawner)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "BndEvt__BP_EternalWatcher_RewardSpawner_K2Node_ComponentBoundEvent_2_AllVisualsHarvestedSignature__DelegateSignature");

	Params::BP_EternalWatcher_C_BndEvt__BP_EternalWatcher_RewardSpawner_K2Node_ComponentBoundEvent_2_AllVisualsHarvestedSignature__DelegateSignature Parms{};

	Parms.InstigateSpawner = InstigateSpawner;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.BPInteractFinished
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AHottaPlayerController*           ByPC                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InteractIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::BPInteractFinished(class AHottaPlayerController* ByPC, int32 InteractIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "BPInteractFinished");

	Params::BP_EternalWatcher_C_BPInteractFinished Parms{};

	Parms.ByPC = ByPC;
	Parms.InteractIndex = InteractIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");

	Params::BP_EternalWatcher_C_BndEvt__BP_EternalWatcher_WatchingBox_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnLoaded_4062BFA74070FE37CF0486B94759CA39
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnLoaded_4062BFA74070FE37CF0486B94759CA39(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnLoaded_4062BFA74070FE37CF0486B94759CA39");

	Params::BP_EternalWatcher_C_OnLoaded_4062BFA74070FE37CF0486B94759CA39 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnLoaded_A3F73B1D42BB935FF3706CA79E1F7CBC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnLoaded_A3F73B1D42BB935FF3706CA79E1F7CBC(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnLoaded_A3F73B1D42BB935FF3706CA79E1F7CBC");

	Params::BP_EternalWatcher_C_OnLoaded_A3F73B1D42BB935FF3706CA79E1F7CBC Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnLoaded_2BB381CB46C56AE86A7BF58D7427FD52
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnLoaded_2BB381CB46C56AE86A7BF58D7427FD52(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnLoaded_2BB381CB46C56AE86A7BF58D7427FD52");

	Params::BP_EternalWatcher_C_OnLoaded_2BB381CB46C56AE86A7BF58D7427FD52 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnLoaded_A4A1E9CF46AFF0352E33B68D1D94814A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnLoaded_A4A1E9CF46AFF0352E33B68D1D94814A(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnLoaded_A4A1E9CF46AFF0352E33B68D1D94814A");

	Params::BP_EternalWatcher_C_OnLoaded_A4A1E9CF46AFF0352E33B68D1D94814A Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_669755B24EF231E23D456C9C47F35C93
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_669755B24EF231E23D456C9C47F35C93(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_669755B24EF231E23D456C9C47F35C93");

	Params::BP_EternalWatcher_C_OnCompleted_669755B24EF231E23D456C9C47F35C93 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_669755B24EF231E23D456C9C47F35C93
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_669755B24EF231E23D456C9C47F35C93(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_669755B24EF231E23D456C9C47F35C93");

	Params::BP_EternalWatcher_C_OnBlendOut_669755B24EF231E23D456C9C47F35C93 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_669755B24EF231E23D456C9C47F35C93
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_669755B24EF231E23D456C9C47F35C93(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_669755B24EF231E23D456C9C47F35C93");

	Params::BP_EternalWatcher_C_OnInterrupted_669755B24EF231E23D456C9C47F35C93 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_669755B24EF231E23D456C9C47F35C93
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_669755B24EF231E23D456C9C47F35C93(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_669755B24EF231E23D456C9C47F35C93");

	Params::BP_EternalWatcher_C_OnNotifyBegin_669755B24EF231E23D456C9C47F35C93 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_669755B24EF231E23D456C9C47F35C93
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_669755B24EF231E23D456C9C47F35C93(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_669755B24EF231E23D456C9C47F35C93");

	Params::BP_EternalWatcher_C_OnNotifyEnd_669755B24EF231E23D456C9C47F35C93 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_D69AC1D64B40C6D852DBE89B1BD5526B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_D69AC1D64B40C6D852DBE89B1BD5526B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_D69AC1D64B40C6D852DBE89B1BD5526B");

	Params::BP_EternalWatcher_C_OnCompleted_D69AC1D64B40C6D852DBE89B1BD5526B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_D69AC1D64B40C6D852DBE89B1BD5526B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_D69AC1D64B40C6D852DBE89B1BD5526B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_D69AC1D64B40C6D852DBE89B1BD5526B");

	Params::BP_EternalWatcher_C_OnBlendOut_D69AC1D64B40C6D852DBE89B1BD5526B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_D69AC1D64B40C6D852DBE89B1BD5526B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_D69AC1D64B40C6D852DBE89B1BD5526B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_D69AC1D64B40C6D852DBE89B1BD5526B");

	Params::BP_EternalWatcher_C_OnInterrupted_D69AC1D64B40C6D852DBE89B1BD5526B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_D69AC1D64B40C6D852DBE89B1BD5526B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_D69AC1D64B40C6D852DBE89B1BD5526B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_D69AC1D64B40C6D852DBE89B1BD5526B");

	Params::BP_EternalWatcher_C_OnNotifyBegin_D69AC1D64B40C6D852DBE89B1BD5526B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_D69AC1D64B40C6D852DBE89B1BD5526B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_D69AC1D64B40C6D852DBE89B1BD5526B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_D69AC1D64B40C6D852DBE89B1BD5526B");

	Params::BP_EternalWatcher_C_OnNotifyEnd_D69AC1D64B40C6D852DBE89B1BD5526B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_C391FAF84C15E05153390BBCF4DFD287
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_C391FAF84C15E05153390BBCF4DFD287(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_C391FAF84C15E05153390BBCF4DFD287");

	Params::BP_EternalWatcher_C_OnCompleted_C391FAF84C15E05153390BBCF4DFD287 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_C391FAF84C15E05153390BBCF4DFD287
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_C391FAF84C15E05153390BBCF4DFD287(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_C391FAF84C15E05153390BBCF4DFD287");

	Params::BP_EternalWatcher_C_OnBlendOut_C391FAF84C15E05153390BBCF4DFD287 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_C391FAF84C15E05153390BBCF4DFD287
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_C391FAF84C15E05153390BBCF4DFD287(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_C391FAF84C15E05153390BBCF4DFD287");

	Params::BP_EternalWatcher_C_OnInterrupted_C391FAF84C15E05153390BBCF4DFD287 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_C391FAF84C15E05153390BBCF4DFD287
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_C391FAF84C15E05153390BBCF4DFD287(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_C391FAF84C15E05153390BBCF4DFD287");

	Params::BP_EternalWatcher_C_OnNotifyBegin_C391FAF84C15E05153390BBCF4DFD287 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_C391FAF84C15E05153390BBCF4DFD287
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_C391FAF84C15E05153390BBCF4DFD287(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_C391FAF84C15E05153390BBCF4DFD287");

	Params::BP_EternalWatcher_C_OnNotifyEnd_C391FAF84C15E05153390BBCF4DFD287 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_095E0262457F69D4DDB9CB9CE56D986B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_095E0262457F69D4DDB9CB9CE56D986B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_095E0262457F69D4DDB9CB9CE56D986B");

	Params::BP_EternalWatcher_C_OnCompleted_095E0262457F69D4DDB9CB9CE56D986B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_095E0262457F69D4DDB9CB9CE56D986B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_095E0262457F69D4DDB9CB9CE56D986B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_095E0262457F69D4DDB9CB9CE56D986B");

	Params::BP_EternalWatcher_C_OnBlendOut_095E0262457F69D4DDB9CB9CE56D986B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_095E0262457F69D4DDB9CB9CE56D986B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_095E0262457F69D4DDB9CB9CE56D986B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_095E0262457F69D4DDB9CB9CE56D986B");

	Params::BP_EternalWatcher_C_OnInterrupted_095E0262457F69D4DDB9CB9CE56D986B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_095E0262457F69D4DDB9CB9CE56D986B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_095E0262457F69D4DDB9CB9CE56D986B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_095E0262457F69D4DDB9CB9CE56D986B");

	Params::BP_EternalWatcher_C_OnNotifyBegin_095E0262457F69D4DDB9CB9CE56D986B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_095E0262457F69D4DDB9CB9CE56D986B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_095E0262457F69D4DDB9CB9CE56D986B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_095E0262457F69D4DDB9CB9CE56D986B");

	Params::BP_EternalWatcher_C_OnNotifyEnd_095E0262457F69D4DDB9CB9CE56D986B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_71D8F6D14F257215D21F979FB2643EAD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_71D8F6D14F257215D21F979FB2643EAD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_71D8F6D14F257215D21F979FB2643EAD");

	Params::BP_EternalWatcher_C_OnCompleted_71D8F6D14F257215D21F979FB2643EAD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_71D8F6D14F257215D21F979FB2643EAD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_71D8F6D14F257215D21F979FB2643EAD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_71D8F6D14F257215D21F979FB2643EAD");

	Params::BP_EternalWatcher_C_OnBlendOut_71D8F6D14F257215D21F979FB2643EAD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_71D8F6D14F257215D21F979FB2643EAD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_71D8F6D14F257215D21F979FB2643EAD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_71D8F6D14F257215D21F979FB2643EAD");

	Params::BP_EternalWatcher_C_OnInterrupted_71D8F6D14F257215D21F979FB2643EAD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_71D8F6D14F257215D21F979FB2643EAD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_71D8F6D14F257215D21F979FB2643EAD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_71D8F6D14F257215D21F979FB2643EAD");

	Params::BP_EternalWatcher_C_OnNotifyBegin_71D8F6D14F257215D21F979FB2643EAD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_71D8F6D14F257215D21F979FB2643EAD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_71D8F6D14F257215D21F979FB2643EAD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_71D8F6D14F257215D21F979FB2643EAD");

	Params::BP_EternalWatcher_C_OnNotifyEnd_71D8F6D14F257215D21F979FB2643EAD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_171C4AC34735BB7D6B3ADFA9127E63C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_171C4AC34735BB7D6B3ADFA9127E63C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_171C4AC34735BB7D6B3ADFA9127E63C5");

	Params::BP_EternalWatcher_C_OnCompleted_171C4AC34735BB7D6B3ADFA9127E63C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_171C4AC34735BB7D6B3ADFA9127E63C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_171C4AC34735BB7D6B3ADFA9127E63C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_171C4AC34735BB7D6B3ADFA9127E63C5");

	Params::BP_EternalWatcher_C_OnBlendOut_171C4AC34735BB7D6B3ADFA9127E63C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_171C4AC34735BB7D6B3ADFA9127E63C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_171C4AC34735BB7D6B3ADFA9127E63C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_171C4AC34735BB7D6B3ADFA9127E63C5");

	Params::BP_EternalWatcher_C_OnInterrupted_171C4AC34735BB7D6B3ADFA9127E63C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_171C4AC34735BB7D6B3ADFA9127E63C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_171C4AC34735BB7D6B3ADFA9127E63C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_171C4AC34735BB7D6B3ADFA9127E63C5");

	Params::BP_EternalWatcher_C_OnNotifyBegin_171C4AC34735BB7D6B3ADFA9127E63C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_171C4AC34735BB7D6B3ADFA9127E63C5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_171C4AC34735BB7D6B3ADFA9127E63C5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_171C4AC34735BB7D6B3ADFA9127E63C5");

	Params::BP_EternalWatcher_C_OnNotifyEnd_171C4AC34735BB7D6B3ADFA9127E63C5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_51BB85B349B066F1786A1DBB5203369A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_51BB85B349B066F1786A1DBB5203369A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_51BB85B349B066F1786A1DBB5203369A");

	Params::BP_EternalWatcher_C_OnCompleted_51BB85B349B066F1786A1DBB5203369A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_51BB85B349B066F1786A1DBB5203369A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_51BB85B349B066F1786A1DBB5203369A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_51BB85B349B066F1786A1DBB5203369A");

	Params::BP_EternalWatcher_C_OnBlendOut_51BB85B349B066F1786A1DBB5203369A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_51BB85B349B066F1786A1DBB5203369A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_51BB85B349B066F1786A1DBB5203369A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_51BB85B349B066F1786A1DBB5203369A");

	Params::BP_EternalWatcher_C_OnInterrupted_51BB85B349B066F1786A1DBB5203369A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_51BB85B349B066F1786A1DBB5203369A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_51BB85B349B066F1786A1DBB5203369A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_51BB85B349B066F1786A1DBB5203369A");

	Params::BP_EternalWatcher_C_OnNotifyBegin_51BB85B349B066F1786A1DBB5203369A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_51BB85B349B066F1786A1DBB5203369A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_51BB85B349B066F1786A1DBB5203369A(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_51BB85B349B066F1786A1DBB5203369A");

	Params::BP_EternalWatcher_C_OnNotifyEnd_51BB85B349B066F1786A1DBB5203369A Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_86AA963041F949FBC97E04BE92ACBCD5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_86AA963041F949FBC97E04BE92ACBCD5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_86AA963041F949FBC97E04BE92ACBCD5");

	Params::BP_EternalWatcher_C_OnCompleted_86AA963041F949FBC97E04BE92ACBCD5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_86AA963041F949FBC97E04BE92ACBCD5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_86AA963041F949FBC97E04BE92ACBCD5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_86AA963041F949FBC97E04BE92ACBCD5");

	Params::BP_EternalWatcher_C_OnBlendOut_86AA963041F949FBC97E04BE92ACBCD5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_86AA963041F949FBC97E04BE92ACBCD5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_86AA963041F949FBC97E04BE92ACBCD5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_86AA963041F949FBC97E04BE92ACBCD5");

	Params::BP_EternalWatcher_C_OnInterrupted_86AA963041F949FBC97E04BE92ACBCD5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_86AA963041F949FBC97E04BE92ACBCD5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_86AA963041F949FBC97E04BE92ACBCD5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_86AA963041F949FBC97E04BE92ACBCD5");

	Params::BP_EternalWatcher_C_OnNotifyBegin_86AA963041F949FBC97E04BE92ACBCD5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_86AA963041F949FBC97E04BE92ACBCD5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_86AA963041F949FBC97E04BE92ACBCD5(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_86AA963041F949FBC97E04BE92ACBCD5");

	Params::BP_EternalWatcher_C_OnNotifyEnd_86AA963041F949FBC97E04BE92ACBCD5 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_18FF73C14BE20F86EB986BBD294DA19B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_18FF73C14BE20F86EB986BBD294DA19B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_18FF73C14BE20F86EB986BBD294DA19B");

	Params::BP_EternalWatcher_C_OnCompleted_18FF73C14BE20F86EB986BBD294DA19B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_18FF73C14BE20F86EB986BBD294DA19B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_18FF73C14BE20F86EB986BBD294DA19B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_18FF73C14BE20F86EB986BBD294DA19B");

	Params::BP_EternalWatcher_C_OnBlendOut_18FF73C14BE20F86EB986BBD294DA19B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_18FF73C14BE20F86EB986BBD294DA19B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_18FF73C14BE20F86EB986BBD294DA19B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_18FF73C14BE20F86EB986BBD294DA19B");

	Params::BP_EternalWatcher_C_OnInterrupted_18FF73C14BE20F86EB986BBD294DA19B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_18FF73C14BE20F86EB986BBD294DA19B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_18FF73C14BE20F86EB986BBD294DA19B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_18FF73C14BE20F86EB986BBD294DA19B");

	Params::BP_EternalWatcher_C_OnNotifyBegin_18FF73C14BE20F86EB986BBD294DA19B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_18FF73C14BE20F86EB986BBD294DA19B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_18FF73C14BE20F86EB986BBD294DA19B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_18FF73C14BE20F86EB986BBD294DA19B");

	Params::BP_EternalWatcher_C_OnNotifyEnd_18FF73C14BE20F86EB986BBD294DA19B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_F36ED7EC4DAF8EBF76E790987F2B29FD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_F36ED7EC4DAF8EBF76E790987F2B29FD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_F36ED7EC4DAF8EBF76E790987F2B29FD");

	Params::BP_EternalWatcher_C_OnCompleted_F36ED7EC4DAF8EBF76E790987F2B29FD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_F36ED7EC4DAF8EBF76E790987F2B29FD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_F36ED7EC4DAF8EBF76E790987F2B29FD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_F36ED7EC4DAF8EBF76E790987F2B29FD");

	Params::BP_EternalWatcher_C_OnBlendOut_F36ED7EC4DAF8EBF76E790987F2B29FD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_F36ED7EC4DAF8EBF76E790987F2B29FD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_F36ED7EC4DAF8EBF76E790987F2B29FD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_F36ED7EC4DAF8EBF76E790987F2B29FD");

	Params::BP_EternalWatcher_C_OnInterrupted_F36ED7EC4DAF8EBF76E790987F2B29FD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_F36ED7EC4DAF8EBF76E790987F2B29FD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_F36ED7EC4DAF8EBF76E790987F2B29FD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_F36ED7EC4DAF8EBF76E790987F2B29FD");

	Params::BP_EternalWatcher_C_OnNotifyBegin_F36ED7EC4DAF8EBF76E790987F2B29FD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_F36ED7EC4DAF8EBF76E790987F2B29FD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_F36ED7EC4DAF8EBF76E790987F2B29FD(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_F36ED7EC4DAF8EBF76E790987F2B29FD");

	Params::BP_EternalWatcher_C_OnNotifyEnd_F36ED7EC4DAF8EBF76E790987F2B29FD Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_22BCBEF44DDE4F2323212E9C2DA69D38
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_22BCBEF44DDE4F2323212E9C2DA69D38(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_22BCBEF44DDE4F2323212E9C2DA69D38");

	Params::BP_EternalWatcher_C_OnCompleted_22BCBEF44DDE4F2323212E9C2DA69D38 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_22BCBEF44DDE4F2323212E9C2DA69D38
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_22BCBEF44DDE4F2323212E9C2DA69D38(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_22BCBEF44DDE4F2323212E9C2DA69D38");

	Params::BP_EternalWatcher_C_OnBlendOut_22BCBEF44DDE4F2323212E9C2DA69D38 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_22BCBEF44DDE4F2323212E9C2DA69D38
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_22BCBEF44DDE4F2323212E9C2DA69D38(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_22BCBEF44DDE4F2323212E9C2DA69D38");

	Params::BP_EternalWatcher_C_OnInterrupted_22BCBEF44DDE4F2323212E9C2DA69D38 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_22BCBEF44DDE4F2323212E9C2DA69D38
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_22BCBEF44DDE4F2323212E9C2DA69D38(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_22BCBEF44DDE4F2323212E9C2DA69D38");

	Params::BP_EternalWatcher_C_OnNotifyBegin_22BCBEF44DDE4F2323212E9C2DA69D38 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_22BCBEF44DDE4F2323212E9C2DA69D38
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_22BCBEF44DDE4F2323212E9C2DA69D38(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_22BCBEF44DDE4F2323212E9C2DA69D38");

	Params::BP_EternalWatcher_C_OnNotifyEnd_22BCBEF44DDE4F2323212E9C2DA69D38 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_FDBE6A52443C293992C4AF86325FBAC2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_FDBE6A52443C293992C4AF86325FBAC2(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_FDBE6A52443C293992C4AF86325FBAC2");

	Params::BP_EternalWatcher_C_OnCompleted_FDBE6A52443C293992C4AF86325FBAC2 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_FDBE6A52443C293992C4AF86325FBAC2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_FDBE6A52443C293992C4AF86325FBAC2(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_FDBE6A52443C293992C4AF86325FBAC2");

	Params::BP_EternalWatcher_C_OnBlendOut_FDBE6A52443C293992C4AF86325FBAC2 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_FDBE6A52443C293992C4AF86325FBAC2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_FDBE6A52443C293992C4AF86325FBAC2(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_FDBE6A52443C293992C4AF86325FBAC2");

	Params::BP_EternalWatcher_C_OnInterrupted_FDBE6A52443C293992C4AF86325FBAC2 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_FDBE6A52443C293992C4AF86325FBAC2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_FDBE6A52443C293992C4AF86325FBAC2(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_FDBE6A52443C293992C4AF86325FBAC2");

	Params::BP_EternalWatcher_C_OnNotifyBegin_FDBE6A52443C293992C4AF86325FBAC2 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_FDBE6A52443C293992C4AF86325FBAC2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_FDBE6A52443C293992C4AF86325FBAC2(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_FDBE6A52443C293992C4AF86325FBAC2");

	Params::BP_EternalWatcher_C_OnNotifyEnd_FDBE6A52443C293992C4AF86325FBAC2 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_17A446154F9863FF178D62A951286E55
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_17A446154F9863FF178D62A951286E55(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_17A446154F9863FF178D62A951286E55");

	Params::BP_EternalWatcher_C_OnCompleted_17A446154F9863FF178D62A951286E55 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_17A446154F9863FF178D62A951286E55
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_17A446154F9863FF178D62A951286E55(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_17A446154F9863FF178D62A951286E55");

	Params::BP_EternalWatcher_C_OnBlendOut_17A446154F9863FF178D62A951286E55 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_17A446154F9863FF178D62A951286E55
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_17A446154F9863FF178D62A951286E55(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_17A446154F9863FF178D62A951286E55");

	Params::BP_EternalWatcher_C_OnInterrupted_17A446154F9863FF178D62A951286E55 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_17A446154F9863FF178D62A951286E55
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_17A446154F9863FF178D62A951286E55(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_17A446154F9863FF178D62A951286E55");

	Params::BP_EternalWatcher_C_OnNotifyBegin_17A446154F9863FF178D62A951286E55 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_17A446154F9863FF178D62A951286E55
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_17A446154F9863FF178D62A951286E55(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_17A446154F9863FF178D62A951286E55");

	Params::BP_EternalWatcher_C_OnNotifyEnd_17A446154F9863FF178D62A951286E55 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_BB54918A407D5140E89E6382C0CE3388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_BB54918A407D5140E89E6382C0CE3388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_BB54918A407D5140E89E6382C0CE3388");

	Params::BP_EternalWatcher_C_OnCompleted_BB54918A407D5140E89E6382C0CE3388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_BB54918A407D5140E89E6382C0CE3388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_BB54918A407D5140E89E6382C0CE3388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_BB54918A407D5140E89E6382C0CE3388");

	Params::BP_EternalWatcher_C_OnBlendOut_BB54918A407D5140E89E6382C0CE3388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_BB54918A407D5140E89E6382C0CE3388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_BB54918A407D5140E89E6382C0CE3388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_BB54918A407D5140E89E6382C0CE3388");

	Params::BP_EternalWatcher_C_OnInterrupted_BB54918A407D5140E89E6382C0CE3388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_BB54918A407D5140E89E6382C0CE3388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_BB54918A407D5140E89E6382C0CE3388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_BB54918A407D5140E89E6382C0CE3388");

	Params::BP_EternalWatcher_C_OnNotifyBegin_BB54918A407D5140E89E6382C0CE3388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_BB54918A407D5140E89E6382C0CE3388
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_BB54918A407D5140E89E6382C0CE3388(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_BB54918A407D5140E89E6382C0CE3388");

	Params::BP_EternalWatcher_C_OnNotifyEnd_BB54918A407D5140E89E6382C0CE3388 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_16B3D308427CAEB4C85E76B9FEE7B523
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_16B3D308427CAEB4C85E76B9FEE7B523(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_16B3D308427CAEB4C85E76B9FEE7B523");

	Params::BP_EternalWatcher_C_OnCompleted_16B3D308427CAEB4C85E76B9FEE7B523 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_16B3D308427CAEB4C85E76B9FEE7B523
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_16B3D308427CAEB4C85E76B9FEE7B523(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_16B3D308427CAEB4C85E76B9FEE7B523");

	Params::BP_EternalWatcher_C_OnBlendOut_16B3D308427CAEB4C85E76B9FEE7B523 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_16B3D308427CAEB4C85E76B9FEE7B523
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_16B3D308427CAEB4C85E76B9FEE7B523(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_16B3D308427CAEB4C85E76B9FEE7B523");

	Params::BP_EternalWatcher_C_OnInterrupted_16B3D308427CAEB4C85E76B9FEE7B523 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_16B3D308427CAEB4C85E76B9FEE7B523
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_16B3D308427CAEB4C85E76B9FEE7B523(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_16B3D308427CAEB4C85E76B9FEE7B523");

	Params::BP_EternalWatcher_C_OnNotifyBegin_16B3D308427CAEB4C85E76B9FEE7B523 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_16B3D308427CAEB4C85E76B9FEE7B523
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_16B3D308427CAEB4C85E76B9FEE7B523(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_16B3D308427CAEB4C85E76B9FEE7B523");

	Params::BP_EternalWatcher_C_OnNotifyEnd_16B3D308427CAEB4C85E76B9FEE7B523 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnCompleted_C7751CCF450AEB2D19CB84BFB68B9F2B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnCompleted_C7751CCF450AEB2D19CB84BFB68B9F2B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnCompleted_C7751CCF450AEB2D19CB84BFB68B9F2B");

	Params::BP_EternalWatcher_C_OnCompleted_C7751CCF450AEB2D19CB84BFB68B9F2B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnBlendOut_C7751CCF450AEB2D19CB84BFB68B9F2B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnBlendOut_C7751CCF450AEB2D19CB84BFB68B9F2B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnBlendOut_C7751CCF450AEB2D19CB84BFB68B9F2B");

	Params::BP_EternalWatcher_C_OnBlendOut_C7751CCF450AEB2D19CB84BFB68B9F2B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnInterrupted_C7751CCF450AEB2D19CB84BFB68B9F2B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnInterrupted_C7751CCF450AEB2D19CB84BFB68B9F2B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnInterrupted_C7751CCF450AEB2D19CB84BFB68B9F2B");

	Params::BP_EternalWatcher_C_OnInterrupted_C7751CCF450AEB2D19CB84BFB68B9F2B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyBegin_C7751CCF450AEB2D19CB84BFB68B9F2B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyBegin_C7751CCF450AEB2D19CB84BFB68B9F2B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyBegin_C7751CCF450AEB2D19CB84BFB68B9F2B");

	Params::BP_EternalWatcher_C_OnNotifyBegin_C7751CCF450AEB2D19CB84BFB68B9F2B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.OnNotifyEnd_C7751CCF450AEB2D19CB84BFB68B9F2B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EternalWatcher_C::OnNotifyEnd_C7751CCF450AEB2D19CB84BFB68B9F2B(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "OnNotifyEnd_C7751CCF450AEB2D19CB84BFB68B9F2B");

	Params::BP_EternalWatcher_C_OnNotifyEnd_C7751CCF450AEB2D19CB84BFB68B9F2B Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.LookAt__UpdateFunc
// (BlueprintEvent)

void ABP_EternalWatcher_C::LookAt__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "LookAt__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.LookAt__FinishedFunc
// (BlueprintEvent)

void ABP_EternalWatcher_C::LookAt__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "LookAt__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EternalWatcher.BP_EternalWatcher_C.BPGetInteractEntries
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHottaPlayerController*           ByPC                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<struct FInteractEntry>           OutInteractEntries                                     (Parm, OutParm, ContainsInstancedReference)

void ABP_EternalWatcher_C::BPGetInteractEntries(class AHottaPlayerController* ByPC, TArray<struct FInteractEntry>* OutInteractEntries)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EternalWatcher_C", "BPGetInteractEntries");

	Params::BP_EternalWatcher_C_BPGetInteractEntries Parms{};

	Parms.ByPC = ByPC;

	UObject::ProcessEvent(Func, &Parms);

	if (OutInteractEntries != nullptr)
		*OutInteractEntries = std::move(Parms.OutInteractEntries);
}

}

