#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_mon_hum_026_Shake

#include "Basic.hpp"

#include "BP_mon_hum_026_Shake_classes.hpp"
#include "BP_mon_hum_026_Shake_parameters.hpp"


namespace SDK
{

// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.ExecuteUbergraph_BP_mon_hum_026_Shake
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_mon_hum_026_Shake_C::ExecuteUbergraph_BP_mon_hum_026_Shake(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "ExecuteUbergraph_BP_mon_hum_026_Shake");

	Params::BP_mon_hum_026_Shake_C_ExecuteUbergraph_BP_mon_hum_026_Shake Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_EE001FC247BB1C6DF7162DB65683F2B0
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_EE001FC247BB1C6DF7162DB65683F2B0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_EE001FC247BB1C6DF7162DB65683F2B0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_052064FE4FBF4236F3096080CF5C9A42
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_052064FE4FBF4236F3096080CF5C9A42()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_052064FE4FBF4236F3096080CF5C9A42");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_7312D96A48B942CFBBF2D4AD3A24D253
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_7312D96A48B942CFBBF2D4AD3A24D253()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_7312D96A48B942CFBBF2D4AD3A24D253");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_7D39481A4800179A7B3770BFB9C10A3B
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_7D39481A4800179A7B3770BFB9C10A3B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_7D39481A4800179A7B3770BFB9C10A3B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_18B386584030EA6D415DE69FE4CECEB2
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_18B386584030EA6D415DE69FE4CECEB2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_18B386584030EA6D415DE69FE4CECEB2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_643C0D6A43DC5962852B96837A491F38
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_643C0D6A43DC5962852B96837A491F38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_643C0D6A43DC5962852B96837A491F38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_603887B2489CAB1B65DCCD8E6E491BBE
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_603887B2489CAB1B65DCCD8E6E491BBE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_603887B2489CAB1B65DCCD8E6E491BBE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_ACB76F3847E38B8816085F9F2BACE54D
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_ACB76F3847E38B8816085F9F2BACE54D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_ACB76F3847E38B8816085F9F2BACE54D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_9A04505E4126299014219D99373FE88D
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_9A04505E4126299014219D99373FE88D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_9A04505E4126299014219D99373FE88D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_B5D5EA1540FF258D707F08BCB9DDEA6B
// (BlueprintEvent)

void UBP_mon_hum_026_Shake_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_B5D5EA1540FF258D707F08BCB9DDEA6B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BP_mon_hum_026_Shake_AnimGraphNode_ModifyBone_B5D5EA1540FF258D707F08BCB9DDEA6B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UBP_mon_hum_026_Shake_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "AnimGraph");

	Params::BP_mon_hum_026_Shake_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function BP_mon_hum_026_Shake.BP_mon_hum_026_Shake_C.BoneShakeLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   Param_PushScale                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_BlendAlpha                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink                        Param_BoneShakeLayer                                   (Parm, OutParm, NoDestructor)

void UBP_mon_hum_026_Shake_C::BoneShakeLayer(const struct FPoseLink& InPose, float Param_PushScale, float Param_BlendAlpha, struct FPoseLink* Param_BoneShakeLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_mon_hum_026_Shake_C", "BoneShakeLayer");

	Params::BP_mon_hum_026_Shake_C_BoneShakeLayer Parms{};

	Parms.InPose = std::move(InPose);
	Parms.Param_PushScale = Param_PushScale;
	Parms.Param_BlendAlpha = Param_BlendAlpha;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_BoneShakeLayer != nullptr)
		*Param_BoneShakeLayer = std::move(Parms.Param_BoneShakeLayer);
}

}

