#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QRSLCharacterCatchingState

#include "Basic.hpp"

#include "QRSL_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_QRSLCharacterCatchingState.BP_QRSLCharacterCatchingState_C
// 0x0000 (0x0080 - 0x0080)
class UBP_QRSLCharacterCatchingState_C final : public UQRSLCharacterCatchingState
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_QRSLCharacterCatchingState_C">();
	}
	static class UBP_QRSLCharacterCatchingState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_QRSLCharacterCatchingState_C>();
	}
};
static_assert(alignof(UBP_QRSLCharacterCatchingState_C) == 0x000008, "Wrong alignment on UBP_QRSLCharacterCatchingState_C");
static_assert(sizeof(UBP_QRSLCharacterCatchingState_C) == 0x000080, "Wrong size on UBP_QRSLCharacterCatchingState_C");

}

