#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RewardSpawner_InteractAnimal

#include "Basic.hpp"

#include "HottaFramework_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RewardSpawner_InteractAnimal.BP_RewardSpawner_InteractAnimal_C
// 0x0000 (0x03A0 - 0x03A0)
class ABP_RewardSpawner_InteractAnimal_C final : public AHottaVisualSpawnManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RewardSpawner_InteractAnimal_C">();
	}
	static class ABP_RewardSpawner_InteractAnimal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RewardSpawner_InteractAnimal_C>();
	}
};
static_assert(alignof(ABP_RewardSpawner_InteractAnimal_C) == 0x000008, "Wrong alignment on ABP_RewardSpawner_InteractAnimal_C");
static_assert(sizeof(ABP_RewardSpawner_InteractAnimal_C) == 0x0003A0, "Wrong size on ABP_RewardSpawner_InteractAnimal_C");

}

