#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UIMapBackground

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "QRSL_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_UIMapBackground.BP_UIMapBackground_C
// 0x0010 (0x0888 - 0x0878)
class UBP_UIMapBackground_C final : public UQRSLUI_MapBackground
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0878(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_background;                                  // 0x0880(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetMapBackgroundFogMask(class UMapViewComponent* RedrawMapViewComp, float FogRatio, const struct FVector2D& FogOffset);
	void InitOverlay();
	void UpdateVisibility();
	void UpdateMaterial();
	void Construct();
	void OnTextureMatChanged(class AMapBackground* MapBackground);
	void Destruct();
	void OnEndPlay(class AActor* Actor, EEndPlayReason EndPlayReason);
	void On_Appearance_Changed(class AMapBackground* MapBackground);
	void On_Overlay_Changed(class AMapBackground* MapBackground, int32 Level, class UTextureRenderTarget2D* RenderTarget);
	void OnMapBackgroundFogMaskChange____0(class UMapViewComponent* Param_MapViewComp, float FogRatio, const struct FVector2D& FogOffset);
	void ExecuteUbergraph_BP_UIMapBackground(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UIMapBackground_C">();
	}
	static class UBP_UIMapBackground_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UIMapBackground_C>();
	}
};
static_assert(alignof(UBP_UIMapBackground_C) == 0x000008, "Wrong alignment on UBP_UIMapBackground_C");
static_assert(sizeof(UBP_UIMapBackground_C) == 0x000888, "Wrong size on UBP_UIMapBackground_C");
static_assert(offsetof(UBP_UIMapBackground_C, UberGraphFrame) == 0x000878, "Member 'UBP_UIMapBackground_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_UIMapBackground_C, Image_background) == 0x000880, "Member 'UBP_UIMapBackground_C::Image_background' has a wrong offset!");

}

