#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UIMapFog

#include "Basic.hpp"

#include "BP_UIMapFog_classes.hpp"
#include "BP_UIMapFog_parameters.hpp"


namespace SDK
{

// Function BP_UIMapFog.BP_UIMapFog_C.UpdateMaterial
// (Protected, BlueprintCallable, BlueprintEvent)

void UBP_UIMapFog_C::UpdateMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIMapFog_C", "UpdateMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UIMapFog.BP_UIMapFog_C.UpdateFogMaterial
// (Event, Public, BlueprintEvent)

void UBP_UIMapFog_C::UpdateFogMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIMapFog_C", "UpdateFogMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UIMapFog.BP_UIMapFog_C.ExecuteUbergraph_BP_UIMapFog
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UIMapFog_C::ExecuteUbergraph_BP_UIMapFog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIMapFog_C", "ExecuteUbergraph_BP_UIMapFog");

	Params::BP_UIMapFog_C_ExecuteUbergraph_BP_UIMapFog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

