#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_TeleportToLeader

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTTask_TeleportToLeader.BTTask_TeleportToLeader_C
// 0x0008 (0x00B0 - 0x00A8)
class UBTTask_TeleportToLeader_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BTTask_TeleportToLeader(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTTask_TeleportToLeader_C">();
	}
	static class UBTTask_TeleportToLeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTTask_TeleportToLeader_C>();
	}
};
static_assert(alignof(UBTTask_TeleportToLeader_C) == 0x000008, "Wrong alignment on UBTTask_TeleportToLeader_C");
static_assert(sizeof(UBTTask_TeleportToLeader_C) == 0x0000B0, "Wrong size on UBTTask_TeleportToLeader_C");
static_assert(offsetof(UBTTask_TeleportToLeader_C, UberGraphFrame) == 0x0000A8, "Member 'UBTTask_TeleportToLeader_C::UberGraphFrame' has a wrong offset!");

}

