#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: buff_ReliveGod_3s

#include "Basic.hpp"

#include "buff_god_001_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass buff_ReliveGod_3s.buff_ReliveGod_3s_C
// 0x0000 (0x1050 - 0x1050)
class Ubuff_ReliveGod_3s_C final : public Ubuff_god_001_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"buff_ReliveGod_3s_C">();
	}
	static class Ubuff_ReliveGod_3s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ubuff_ReliveGod_3s_C>();
	}
};
static_assert(alignof(Ubuff_ReliveGod_3s_C) == 0x000008, "Wrong alignment on Ubuff_ReliveGod_3s_C");
static_assert(sizeof(Ubuff_ReliveGod_3s_C) == 0x001050, "Wrong size on Ubuff_ReliveGod_3s_C");

}

