#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_BigswordPhy_SR_Level0_1

#include "Basic.hpp"

#include "GE_MeleeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_BigswordPhy_SR_Level0_1.Buff_BigswordPhy_SR_Level0_1_C
// 0x0000 (0x1050 - 0x1050)
class UBuff_BigswordPhy_SR_Level0_1_C final : public UGE_MeleeBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buff_BigswordPhy_SR_Level0_1_C">();
	}
	static class UBuff_BigswordPhy_SR_Level0_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuff_BigswordPhy_SR_Level0_1_C>();
	}
};
static_assert(alignof(UBuff_BigswordPhy_SR_Level0_1_C) == 0x000008, "Wrong alignment on UBuff_BigswordPhy_SR_Level0_1_C");
static_assert(sizeof(UBuff_BigswordPhy_SR_Level0_1_C) == 0x001050, "Wrong size on UBuff_BigswordPhy_SR_Level0_1_C");

}

