#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_DamAdd_Base

#include "Basic.hpp"

#include "GE_MeleeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_DamAdd_Base.Buff_DamAdd_Base_C
// 0x0000 (0x1050 - 0x1050)
class UBuff_DamAdd_Base_C : public UGE_MeleeBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buff_DamAdd_Base_C">();
	}
	static class UBuff_DamAdd_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuff_DamAdd_Base_C>();
	}
};
static_assert(alignof(UBuff_DamAdd_Base_C) == 0x000008, "Wrong alignment on UBuff_DamAdd_Base_C");
static_assert(sizeof(UBuff_DamAdd_Base_C) == 0x001050, "Wrong size on UBuff_DamAdd_Base_C");

}

