#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_MrakRobBranch1_2

#include "Basic.hpp"

#include "Buff_MrakRobBranch1_2_classes.hpp"
#include "Buff_MrakRobBranch1_2_parameters.hpp"


namespace SDK
{

// Function Buff_MrakRobBranch1_2.Buff_MrakRobBranch1_2_C.ExecuteUbergraph_Buff_MrakRobBranch1_2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBuff_MrakRobBranch1_2_C::ExecuteUbergraph_Buff_MrakRobBranch1_2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_MrakRobBranch1_2_C", "ExecuteUbergraph_Buff_MrakRobBranch1_2");

	Params::Buff_MrakRobBranch1_2_C_ExecuteUbergraph_Buff_MrakRobBranch1_2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

