#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_BowFire_SR_Level0_2

#include "Basic.hpp"

#include "GE_MeleeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_BowFire_SR_Level0_2.Buff_BowFire_SR_Level0_2_C
// 0x0000 (0x1050 - 0x1050)
class UBuff_BowFire_SR_Level0_2_C final : public UGE_MeleeBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Buff_BowFire_SR_Level0_2_C">();
	}
	static class UBuff_BowFire_SR_Level0_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuff_BowFire_SR_Level0_2_C>();
	}
};
static_assert(alignof(UBuff_BowFire_SR_Level0_2_C) == 0x000008, "Wrong alignment on UBuff_BowFire_SR_Level0_2_C");
static_assert(sizeof(UBuff_BowFire_SR_Level0_2_C) == 0x001050, "Wrong size on UBuff_BowFire_SR_Level0_2_C");

}

