#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_EleWeakPoint_thunder

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_EleWeakPoint_thunder.Buff_EleWeakPoint_Thunder_C.ExecuteUbergraph_Buff_EleWeakPoint_thunder
// 0x0004 (0x0004 - 0x0000)
struct Buff_EleWeakPoint_Thunder_C_ExecuteUbergraph_Buff_EleWeakPoint_thunder final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Buff_EleWeakPoint_Thunder_C_ExecuteUbergraph_Buff_EleWeakPoint_thunder) == 0x000004, "Wrong alignment on Buff_EleWeakPoint_Thunder_C_ExecuteUbergraph_Buff_EleWeakPoint_thunder");
static_assert(sizeof(Buff_EleWeakPoint_Thunder_C_ExecuteUbergraph_Buff_EleWeakPoint_thunder) == 0x000004, "Wrong size on Buff_EleWeakPoint_Thunder_C_ExecuteUbergraph_Buff_EleWeakPoint_thunder");
static_assert(offsetof(Buff_EleWeakPoint_Thunder_C_ExecuteUbergraph_Buff_EleWeakPoint_thunder, EntryPoint) == 0x000000, "Member 'Buff_EleWeakPoint_Thunder_C_ExecuteUbergraph_Buff_EleWeakPoint_thunder::EntryPoint' has a wrong offset!");

}

