#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_SufferDam_Main

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_SufferDam_Main.Buff_SufferDam_Main_C.ExecuteUbergraph_Buff_SufferDam_Main
// 0x0004 (0x0004 - 0x0000)
struct Buff_SufferDam_Main_C_ExecuteUbergraph_Buff_SufferDam_Main final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Buff_SufferDam_Main_C_ExecuteUbergraph_Buff_SufferDam_Main) == 0x000004, "Wrong alignment on Buff_SufferDam_Main_C_ExecuteUbergraph_Buff_SufferDam_Main");
static_assert(sizeof(Buff_SufferDam_Main_C_ExecuteUbergraph_Buff_SufferDam_Main) == 0x000004, "Wrong size on Buff_SufferDam_Main_C_ExecuteUbergraph_Buff_SufferDam_Main");
static_assert(offsetof(Buff_SufferDam_Main_C_ExecuteUbergraph_Buff_SufferDam_Main, EntryPoint) == 0x000000, "Member 'Buff_SufferDam_Main_C_ExecuteUbergraph_Buff_SufferDam_Main::EntryPoint' has a wrong offset!");

}

