#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChangeWeaponEffectThu

#include "Basic.hpp"

#include "HottaFramework_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ChangeWeaponEffectThu.ChangeWeaponEffectThu_C
// 0x0000 (0x02F0 - 0x02F0)
class AChangeWeaponEffectThu_C final : public AHottaEmitterCameraLensEffectBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChangeWeaponEffectThu_C">();
	}
	static class AChangeWeaponEffectThu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChangeWeaponEffectThu_C>();
	}
};
static_assert(alignof(AChangeWeaponEffectThu_C) == 0x000010, "Wrong alignment on AChangeWeaponEffectThu_C");
static_assert(sizeof(AChangeWeaponEffectThu_C) == 0x0002F0, "Wrong size on AChangeWeaponEffectThu_C");

}

