#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Controller_mon_hum_009

#include "Basic.hpp"

#include "Controller_mon_hum_009_classes.hpp"
#include "Controller_mon_hum_009_parameters.hpp"


namespace SDK
{

// Function Controller_mon_hum_009.Controller_mon_hum_009_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AController_mon_hum_009_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Controller_mon_hum_009_C", "ReceiveTick");

	Params::Controller_mon_hum_009_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Controller_mon_hum_009.Controller_mon_hum_009_C.ExecuteUbergraph_Controller_mon_hum_009
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AController_mon_hum_009_C::ExecuteUbergraph_Controller_mon_hum_009(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Controller_mon_hum_009_C", "ExecuteUbergraph_Controller_mon_hum_009");

	Params::Controller_mon_hum_009_C_ExecuteUbergraph_Controller_mon_hum_009 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

