#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_mimicry_fashion_04_hair_AB

#include "Basic.hpp"

#include "F_mimicry_fashion_04_hair_AB_classes.hpp"
#include "F_mimicry_fashion_04_hair_AB_parameters.hpp"


namespace SDK
{

// Function f_mimicry_fashion_04_hair_AB.f_mimicry_fashion_04_hair_AB_C.ExecuteUbergraph_f_mimicry_fashion_04_hair_AB
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UF_mimicry_fashion_04_hair_AB_C::ExecuteUbergraph_f_mimicry_fashion_04_hair_AB(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("f_mimicry_fashion_04_hair_AB_C", "ExecuteUbergraph_f_mimicry_fashion_04_hair_AB");

	Params::F_mimicry_fashion_04_hair_AB_C_ExecuteUbergraph_f_mimicry_fashion_04_hair_AB Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function f_mimicry_fashion_04_hair_AB.f_mimicry_fashion_04_hair_AB_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UF_mimicry_fashion_04_hair_AB_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("f_mimicry_fashion_04_hair_AB_C", "AnimGraph");

	Params::F_mimicry_fashion_04_hair_AB_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

