#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_Player_QingGongSubAnimGraph

#include "Basic.hpp"

#include "F_Player_QingGongSubAnimGraph_classes.hpp"
#include "F_Player_QingGongSubAnimGraph_parameters.hpp"


namespace SDK
{

// Function F_Player_QingGongSubAnimGraph.F_Player_QingGongSubAnimGraph_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UF_Player_QingGongSubAnimGraph_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_Player_QingGongSubAnimGraph_C", "AnimGraph");

	Params::F_Player_QingGongSubAnimGraph_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function F_Player_QingGongSubAnimGraph.F_Player_QingGongSubAnimGraph_C.EvaluateGraphExposedInputs_ExecuteUbergraph_F_Player_QingGongSubAnimGraph_AnimGraphNode_TransitionResult_C8C750BA4ECDD95DE12FA68EF218D816
// (BlueprintEvent)

void UF_Player_QingGongSubAnimGraph_C::EvaluateGraphExposedInputs_ExecuteUbergraph_F_Player_QingGongSubAnimGraph_AnimGraphNode_TransitionResult_C8C750BA4ECDD95DE12FA68EF218D816()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_Player_QingGongSubAnimGraph_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_F_Player_QingGongSubAnimGraph_AnimGraphNode_TransitionResult_C8C750BA4ECDD95DE12FA68EF218D816");

	UObject::ProcessEvent(Func, nullptr);
}


// Function F_Player_QingGongSubAnimGraph.F_Player_QingGongSubAnimGraph_C.ExecuteUbergraph_F_Player_QingGongSubAnimGraph
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UF_Player_QingGongSubAnimGraph_C::ExecuteUbergraph_F_Player_QingGongSubAnimGraph(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_Player_QingGongSubAnimGraph_C", "ExecuteUbergraph_F_Player_QingGongSubAnimGraph");

	Params::F_Player_QingGongSubAnimGraph_C_ExecuteUbergraph_F_Player_QingGongSubAnimGraph Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

