#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FPA_Snow_BP

#include "Basic.hpp"

#include "FPA_Snow_BP_classes.hpp"
#include "FPA_Snow_BP_parameters.hpp"


namespace SDK
{

// Function FPA_Snow_BP.FPA_Snow_BP_C.ExecuteUbergraph_FPA_Snow_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFPA_Snow_BP_C::ExecuteUbergraph_FPA_Snow_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Snow_BP_C", "ExecuteUbergraph_FPA_Snow_BP");

	Params::FPA_Snow_BP_C_ExecuteUbergraph_FPA_Snow_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPA_Snow_BP.FPA_Snow_BP_C.ReMaintainAndFade
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AFPA_Snow_BP_C::ReMaintainAndFade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Snow_BP_C", "ReMaintainAndFade");

	UObject::ProcessEvent(Func, nullptr);
}

}

