#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FPA_Base_BP

#include "Basic.hpp"

#include "FPA_Base_BP_classes.hpp"
#include "FPA_Base_BP_parameters.hpp"


namespace SDK
{

// Function FPA_Base_BP.FPA_Base_BP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFPA_Base_BP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Base_BP_C", "ReceiveTick");

	Params::FPA_Base_BP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FPA_Base_BP.FPA_Base_BP_C.BegeinFade
// (BlueprintCallable, BlueprintEvent)

void AFPA_Base_BP_C::BegeinFade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Base_BP_C", "BegeinFade");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPA_Base_BP.FPA_Base_BP_C.DestroyFootprint
// (BlueprintCallable, BlueprintEvent)

void AFPA_Base_BP_C::DestroyFootprint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Base_BP_C", "DestroyFootprint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPA_Base_BP.FPA_Base_BP_C.ReMaintainAndFade
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AFPA_Base_BP_C::ReMaintainAndFade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Base_BP_C", "ReMaintainAndFade");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPA_Base_BP.FPA_Base_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AFPA_Base_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Base_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPA_Base_BP.FPA_Base_BP_C.ImmediatelyHide
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AFPA_Base_BP_C::ImmediatelyHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Base_BP_C", "ImmediatelyHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FPA_Base_BP.FPA_Base_BP_C.ExecuteUbergraph_FPA_Base_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AFPA_Base_BP_C::ExecuteUbergraph_FPA_Base_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FPA_Base_BP_C", "ExecuteUbergraph_FPA_Base_BP");

	Params::FPA_Base_BP_C_ExecuteUbergraph_FPA_Base_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

