#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_FPlayerSpearReverseJump

#include "Basic.hpp"

#include "GA_MeleeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_FPlayerSpearReverseJump.GA_FPlayerSpearReverseJump_C
// 0x0000 (0x0D00 - 0x0D00)
class UGA_FPlayerSpearReverseJump_C final : public UGA_MeleeBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_FPlayerSpearReverseJump_C">();
	}
	static class UGA_FPlayerSpearReverseJump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_FPlayerSpearReverseJump_C>();
	}
};
static_assert(alignof(UGA_FPlayerSpearReverseJump_C) == 0x000010, "Wrong alignment on UGA_FPlayerSpearReverseJump_C");
static_assert(sizeof(UGA_FPlayerSpearReverseJump_C) == 0x000D00, "Wrong size on UGA_FPlayerSpearReverseJump_C");

}

