#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_DsAirAttack2_Damage

#include "Basic.hpp"

#include "GE_DsAirAttack1_Damage_SSR_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_DsAirAttack2_Damage.GE_DsAirAttack2_Damage_C
// 0x0000 (0x1050 - 0x1050)
class UGE_DsAirAttack2_Damage_C : public UGE_DsAirAttack1_Damage_SSR_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_DsAirAttack2_Damage_C">();
	}
	static class UGE_DsAirAttack2_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_DsAirAttack2_Damage_C>();
	}
};
static_assert(alignof(UGE_DsAirAttack2_Damage_C) == 0x000008, "Wrong alignment on UGE_DsAirAttack2_Damage_C");
static_assert(sizeof(UGE_DsAirAttack2_Damage_C) == 0x001050, "Wrong size on UGE_DsAirAttack2_Damage_C");

}

