#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_MarkMelee2_HitBack

#include "Basic.hpp"

#include "GE_MeleeBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_MarkMelee2_HitBack.GE_MarkMelee2_HitBack_C
// 0x0000 (0x1050 - 0x1050)
class UGE_MarkMelee2_HitBack_C final : public UGE_MeleeBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_MarkMelee2_HitBack_C">();
	}
	static class UGE_MarkMelee2_HitBack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_MarkMelee2_HitBack_C>();
	}
};
static_assert(alignof(UGE_MarkMelee2_HitBack_C) == 0x000008, "Wrong alignment on UGE_MarkMelee2_HitBack_C");
static_assert(sizeof(UGE_MarkMelee2_HitBack_C) == 0x001050, "Wrong size on UGE_MarkMelee2_HitBack_C");

}

