#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InstancedHarvestComponentBP_muskmelon

#include "Basic.hpp"

#include "InstancedHarvestComponentBP_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InstancedHarvestComponentBP_muskmelon.InstancedHarvestComponentBP_muskmelon_C
// 0x0000 (0x0900 - 0x0900)
class UInstancedHarvestComponentBP_muskmelon_C final : public UInstancedHarvestComponentBP_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"InstancedHarvestComponentBP_muskmelon_C">();
	}
	static class UInstancedHarvestComponentBP_muskmelon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInstancedHarvestComponentBP_muskmelon_C>();
	}
};
static_assert(alignof(UInstancedHarvestComponentBP_muskmelon_C) == 0x000010, "Wrong alignment on UInstancedHarvestComponentBP_muskmelon_C");
static_assert(sizeof(UInstancedHarvestComponentBP_muskmelon_C) == 0x000900, "Wrong size on UInstancedHarvestComponentBP_muskmelon_C");

}

