#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LockRangeSpearMeleePre2

#include "Basic.hpp"

#include "BP_TargetType_LockBoxBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LockRangeSpearMeleePre2.LockRangeSpearMeleePre2_C
// 0x0000 (0x00E8 - 0x00E8)
class ULockRangeSpearMeleePre2_C final : public UBP_TargetType_LockBoxBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LockRangeSpearMeleePre2_C">();
	}
	static class ULockRangeSpearMeleePre2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULockRangeSpearMeleePre2_C>();
	}
};
static_assert(alignof(ULockRangeSpearMeleePre2_C) == 0x000008, "Wrong alignment on ULockRangeSpearMeleePre2_C");
static_assert(sizeof(ULockRangeSpearMeleePre2_C) == 0x0000E8, "Wrong size on ULockRangeSpearMeleePre2_C");

}

