#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LockRangeAirLaunch

#include "Basic.hpp"

#include "BP_TargetType_LockBoxBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LockRangeAirLaunch.LockRangeAirLaunch_C
// 0x0000 (0x00E8 - 0x00E8)
class ULockRangeAirLaunch_C final : public UBP_TargetType_LockBoxBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LockRangeAirLaunch_C">();
	}
	static class ULockRangeAirLaunch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULockRangeAirLaunch_C>();
	}
};
static_assert(alignof(ULockRangeAirLaunch_C) == 0x000008, "Wrong alignment on ULockRangeAirLaunch_C");
static_assert(sizeof(ULockRangeAirLaunch_C) == 0x0000E8, "Wrong size on ULockRangeAirLaunch_C");

}

