#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LockRangeDsChangeSkill_Air

#include "Basic.hpp"

#include "BP_TargetType_LockSphereBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LockRangeDsChangeSkill_Air.LockRangeDsChangeSkill_Air_C
// 0x0000 (0x00E8 - 0x00E8)
class ULockRangeDsChangeSkill_Air_C final : public UBP_TargetType_LockSphereBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LockRangeDsChangeSkill_Air_C">();
	}
	static class ULockRangeDsChangeSkill_Air_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULockRangeDsChangeSkill_Air_C>();
	}
};
static_assert(alignof(ULockRangeDsChangeSkill_Air_C) == 0x000008, "Wrong alignment on ULockRangeDsChangeSkill_Air_C");
static_assert(sizeof(ULockRangeDsChangeSkill_Air_C) == 0x0000E8, "Wrong size on ULockRangeDsChangeSkill_Air_C");

}

