#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MarkRobJumpAttackFloat

#include "Basic.hpp"

#include "HottaFramework_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MarkRobJumpAttackFloat.MarkRobJumpAttackFloat_C
// 0x0000 (0x0140 - 0x0140)
class UMarkRobJumpAttackFloat_C final : public UHottaSkillEffect_HitFloating
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MarkRobJumpAttackFloat_C">();
	}
	static class UMarkRobJumpAttackFloat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMarkRobJumpAttackFloat_C>();
	}
};
static_assert(alignof(UMarkRobJumpAttackFloat_C) == 0x000008, "Wrong alignment on UMarkRobJumpAttackFloat_C");
static_assert(sizeof(UMarkRobJumpAttackFloat_C) == 0x000140, "Wrong size on UMarkRobJumpAttackFloat_C");

}

