#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MarkRobDefaultDamage

#include "Basic.hpp"

#include "DefaultDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MarkRobDefaultDamage.MarkRobDefaultDamage_C
// 0x0000 (0x1050 - 0x1050)
class UMarkRobDefaultDamage_C : public UDefaultDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MarkRobDefaultDamage_C">();
	}
	static class UMarkRobDefaultDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMarkRobDefaultDamage_C>();
	}
};
static_assert(alignof(UMarkRobDefaultDamage_C) == 0x000008, "Wrong alignment on UMarkRobDefaultDamage_C");
static_assert(sizeof(UMarkRobDefaultDamage_C) == 0x001050, "Wrong size on UMarkRobDefaultDamage_C");

}

