#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Muzhuang

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Mon_hum_083_big_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass muzhuang.muzhuang_C
// 0x0000 (0x3B30 - 0x3B30)
class AMuzhuang_C final : public AMon_hum_083_big_C
{
public:
	uint8                                         Pad_555B[0x4];                                     // 0x3B24(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_Muzhuang_C;                         // 0x3B28(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_muzhuang(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"muzhuang_C">();
	}
	static class AMuzhuang_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMuzhuang_C>();
	}
};
static_assert(alignof(AMuzhuang_C) == 0x000010, "Wrong alignment on AMuzhuang_C");
static_assert(sizeof(AMuzhuang_C) == 0x003B30, "Wrong size on AMuzhuang_C");
static_assert(offsetof(AMuzhuang_C, UberGraphFrame_Muzhuang_C) == 0x003B28, "Member 'AMuzhuang_C::UberGraphFrame_Muzhuang_C' has a wrong offset!");

}

