#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FriendSlot

#include "Basic.hpp"

#include "QRSL_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_FriendSlot.UI_FriendSlot_C
// 0x0010 (0x0AD0 - 0x0AC0)
class UUI_FriendSlot_C final : public UQRSLUI_FriendSlot
{
public:
	class UImage*                                 Image_325;                                         // 0x0AC0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_421;                                         // 0x0AC8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_FriendSlot_C">();
	}
	static class UUI_FriendSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_FriendSlot_C>();
	}
};
static_assert(alignof(UUI_FriendSlot_C) == 0x000008, "Wrong alignment on UUI_FriendSlot_C");
static_assert(sizeof(UUI_FriendSlot_C) == 0x000AD0, "Wrong size on UUI_FriendSlot_C");
static_assert(offsetof(UUI_FriendSlot_C, Image_325) == 0x000AC0, "Member 'UUI_FriendSlot_C::Image_325' has a wrong offset!");
static_assert(offsetof(UUI_FriendSlot_C, Image_421) == 0x000AC8, "Member 'UUI_FriendSlot_C::Image_421' has a wrong offset!");

}

