#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_TeamFightRankWidget

#include "Basic.hpp"

#include "QRSL_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_TeamFightRankWidget.UI_TeamFightRankWidget_C
// 0x0000 (0x08A0 - 0x08A0)
class UUI_TeamFightRankWidget_C final : public UQRSLUI_WorldBossRankWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_TeamFightRankWidget_C">();
	}
	static class UUI_TeamFightRankWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_TeamFightRankWidget_C>();
	}
};
static_assert(alignof(UUI_TeamFightRankWidget_C) == 0x000008, "Wrong alignment on UUI_TeamFightRankWidget_C");
static_assert(sizeof(UUI_TeamFightRankWidget_C) == 0x0008A0, "Wrong size on UUI_TeamFightRankWidget_C");

}

