#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_sw02BPThu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WeaponMelee_SingleHandBP_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Weapon_sw02BPThu.Weapon_sw02BPThu_C
// 0x0010 (0x1340 - 0x1330)
#pragma pack(push, 0x1)
class alignas(0x10) AWeapon_sw02BPThu_C : public AWeaponMelee_SingleHandBP_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Weapon_sw02BPThu_C;                 // 0x1328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               Weapon_FX;                                         // 0x1330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Weapon_sw02BPThu(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Weapon_sw02BPThu_C">();
	}
	static class AWeapon_sw02BPThu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapon_sw02BPThu_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(AWeapon_sw02BPThu_C) == 0x000010, "Wrong alignment on AWeapon_sw02BPThu_C");
static_assert(sizeof(AWeapon_sw02BPThu_C) == 0x001340, "Wrong size on AWeapon_sw02BPThu_C");
static_assert(offsetof(AWeapon_sw02BPThu_C, UberGraphFrame_Weapon_sw02BPThu_C) == 0x001328, "Member 'AWeapon_sw02BPThu_C::UberGraphFrame_Weapon_sw02BPThu_C' has a wrong offset!");
static_assert(offsetof(AWeapon_sw02BPThu_C, Weapon_FX) == 0x001330, "Member 'AWeapon_sw02BPThu_C::Weapon_FX' has a wrong offset!");

}

